backend:
  name: github
  repo: Omid-Vahdat-collab/my-site
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "کتاب‌ها"
    folder: "content/posts"
    create: true
    fields:
      - {label: "عنوان", name: "title", widget: "string"}
      - {label: "تاریخ", name: "date", widget: "datetime"}
      - {label: "پیش‌نویس", name: "draft", widget: "boolean", default: false}
      - {label: "متن", name: "body", widget: "markdown"}
